title: SCI VIS Paper Discussion
description: This is the repository of VIS paper in group seminar. Adviorsed by <a herf="www.google.com">Prof. Chris Johnson</a>.
show_downloads: false
google_analytics:
theme:

